### ISSUE TITLE
Add 'all' to WHEEL_TYPE

### ISSUE THREAD

**Issue by bsipocz** [MacPython/terryfy#13]
Currently one has to loop through ``['macosx', 'win', 'manylinux1','linux']`` to get all the wheels before uploading them to pypi, would be nice to have an ``'all'`` option, too

**Comment by peterjc** [comment]
Or the option to supply a list at the command line, e.g.

```
$ wheel-uploader -t macox,win,manylinux1 PROJECT VERSION
```

vs:

```
$ wheel-uploader -t macox PROJECT VERSION
$ wheel-uploader -t win PROJECT VERSION
$ wheel-uploader -t manylinux1 PROJECT VERSION
```

**Comment by matthew-brett** [comment]
Anyone see a problem with : https://github.com/MacPython/terryfy/pull/14 ?

**Comment by matthew-brett** [comment]
OK to close this one?

**Comment by peterjc** [comment]
Adding "all" seems to cover this, thanks!

**Comment by matthew-brett** [comment]
Thanks, closing.
