### ISSUE TITLE
Homebrew python updates

### ISSUE THREAD

**Issue by illume** [MacPython/terryfy#16]
Hi,

python has been changed on homebrew. 

- now python 2 needs `brew install python@2`
- python2 and pip2 are not on the path anymore. 
- Also the path has changed: `/usr/local/opt/python@2/bin`

Both python 2 and 3 seem to not install anymore with:
```
get_python_environment homebrew $PY_VERSION $(pwd)/_test_env
```

PY_VERSION 3 error...
https://travis-ci.org/pygame/pygame/jobs/349317960#L3485

PY_VERSION 2 error...
https://travis-ci.org/pygame/pygame/jobs/349372098#L3580

cheers,

**Comment by matthew-brett** [comment]
So sorry to be slow on this - I think current master works - do you agree?

**Comment by matthew-brett** [comment]
Current testing passes with homebrew Pythons 2 and 3, so assuming this fixed.  Please re-open if I'm wrong.
