### ISSUE TITLE
sudoless terryfy?

### ISSUE THREAD

**Issue by ariddell** [MacPython/terryfy#2]
Is it possible to avoid using sudo in ``get_python_environment`` or would that be an epic amount of work.

Wondering as I've seen the messages from travis-ci on non-OS-X builds suggesting to avoid using sudo in order to use their new build system.

**Comment by matthew-brett** [comment]
I believe the non sudo builds use docker on Linux and so cannot work on osx
because osx does not support docker.

**Comment by ariddell** [comment]
That makes sense. Thanks!
