### ISSUE TITLE
Support for python 3.8

### ISSUE THREAD

**Issue by fgregg** [MacPython/terryfy#20]
Thanks for a great tool.

Unfortunately, it does not work for python 3.8. I think this *might* be fixed with by updating the macports version.

https://github.com/MacPython/terryfy/blob/f8ab4fa7cc02d7a1116359dfc58e4dfdb1c965bd/travis_tools.sh#L23

**Comment by matthew-brett** [comment]
Thanks - I'm giving this a shot over at #21

**Comment by matthew-brett** [comment]
I think it's working on current master now - let me know?

**Comment by fgregg** [comment]
works great, thanks!
