### ISSUE TITLE
[feature req.] add support for installing PyPy with travis_tools.sh

### ISSUE THREAD

**Issue by anthrotype** [MacPython/terryfy#3]
That would be cool.
If it's not too difficult I may give it a try.
thanks a lot for this great collection of utilities.
Cheers,

Cosimo

**Comment by matthew-brett** [comment]
I don't think it would be very difficult - but I don't know Pypy at all.

Would you mind having a go?

**Comment by matthew-brett** [comment]
This is now in https://github.com/matthew-brett/multibuild, so closing here.  Please reopen if you still want the functionality in Terryfy specifically.
