### ISSUE TITLE
Seeing 'remove_travis_ve_pip: command not found'

### ISSUE THREAD

**Issue by andrewferrier** [MacPython/terryfy#5]
My .travis.yml looks like this:

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/MacPython/terryfy; git checkout fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/travis_tools.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then get_python_environment macports $TRAVIS_PYTHON_VERSION env/; fi

As of commit 34d7997a, I'm seeing an error like this on build:

terryfy/travis_tools.sh: line 220: remove_travis_ve_pip: command not found
usage: mkdir [-pv] [-m mode] directory ...
terryfy/travis_tools.sh: line 71: /MacPorts-2.3.3-10.9-Mavericks.pkg: Permission denied
failed to download macports

Looks like maybe a call to remove_travis_ve_pip was added, but not the command itself?

Thanks for terryfy, it's a useful utility!

**Comment by andrewferrier** [comment]
FYI, if I use the "third" release/tag, it works w/o this error.

**Comment by andrewferrier** [comment]
Full failure is here if it helps: https://travis-ci.org/andrewferrier/normalize-filename/jobs/138121951.

**Comment by matthew-brett** [comment]
Ah - thanks - I think I've fixed it - would you mind triggering your build again to test?

**Comment by andrewferrier** [comment]
Works great - thanks! https://travis-ci.org/andrewferrier/normalize-filename/builds/138152271.
